dev_mode: true
server:
  external:
    domain: "127.0.0.1:8080"
    host: "127.0.0.1"
    port:
      connect: 8080
      metric: 8081
storage:
  root: "../cache"
  urls:
    - "https://github.com/bufbuild/protoc-gen-validate.git"
    - "https://github.com/RussianInvestments/invest-api-go-sdk.git"
