run:
  timeout: 5m
  # include test files
  tests: true
  # skipping non-go dirs
  skip-dirs:
    - bin
    - config
    - debian
    - docs
    - scripts
    - tests

linters:
  enable-all: true
  disable:
    - exhaustivestruct # The owner seems to have abandoned the linter. Replaced by exhaustruct.
    - ifshort          # The repository of the linter has been deprecated by the owner.
    - maligned         # The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'.
    - interfacer       # The repository of the linter has been archived by the owner.
    - deadcode         # The owner seems to have abandoned the linter. Replaced by unused.
    - golint           # The repository of the linter has been archived by the owner. Replaced by revive.
    - varcheck         # The owner seems to have abandoned the linter. Replaced by unused.
    - structcheck      # The owner seems to have abandoned the linter. Replaced by unused.
    - nosnakecase      # The repository of the linter has been deprecated by the owner. Replaced by revive(var-naming).
    - scopelint        # The repository of the linter has been deprecated by the owner. Replaced by exportloopref.
    - varnamelen # useless in the scope of this project

  # Run all the linters from enabled linters set
  fast: false

issues:
  include:
    - EXC0001 # Check return values of os funcs
    - EXC0004 # govet
    - EXC0005 # C-style breaks
  exclude:

  exclude-rules:
    - linters:
        - ireturn
      text: "returns generic interface"
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - revive
      text: "unexported-return: exported func .+ returns unexported type .+, which can be annoying to use"
    - path: cmd/[^/]+/.+\.go
      text: exitAfterDefer
      liners:
        - gocritic
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - exhaustruct
        - ireturn
        - funlen
        - unparam
        - lll

linters-settings:
  gci:
    # Section configuration to compare against.
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/easyp-tech) # Custom section: groups all imports with the specified Prefix.
    skip-generated: false
    # Enable custom order of sections.
    # If true, make the section order the same as the order of sections.
    custom-order: true
  depguard:
      rules:
        main:
          files:
            - !$test
          allow:
            - $gostd
        cmd:
          files:
            - "cmd/*/*.go"
          allow:
            - $gostd
        tests:
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr/testify
