run:
  tests: false

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Files with go:embed directives are designed to contain global constants.
    - path: main\.go|^(.*/)?embeded.go$
      linters:
        - gochecknoglobals

linters-settings:
  cyclop:
    max-complexity: 20

  stylecheck:
    # https://staticcheck.io/docs/options#checks
    # Default: ["*"]
    checks: [ "-ST1000", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    # Default: ["github.com/mmcloughlin/avo/build", "github.com/mmcloughlin/avo/operand", "github.com/mmcloughlin/avo/reg"]
    dot-import-whitelist:
      - fmt
    # https://staticcheck.io/docs/options#initialisms
    # Default: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS"]
    initialisms: [ "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS" ]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    # Default: ["200", "400", "404", "500"]
    http-status-code-whitelist: [ "200", "400", "404", "500" ]

  funlen:
    lines: 80
    statements: 40

  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      # Rules ported from golint:
      - name: context-keys-type
      - name: time-naming
      - name: var-declaration
      - name: unexported-return
      - name: errorf
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      #- name: exported
      - name: if-return
      - name: increment-decrement
        #      - name: var-naming
        #arguments: # First list element is a whitelist, second is a blacklist.
        #  - ["ID"] # whitelist
        #  - ["VM"] # blacklist
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      # Rules not available in golint:
      #- name: argument-limit
      #  arguments: 4
      #- name: cyclomatic
      #  arguments: 15
      #- name: max-public-structs
      #  arguments: 3
      #- name: file-header
      #  arguments: "This is the text that must appear at the top of source files."
      #- name: empty-block # See https://github.com/mgechev/revive/issues/386
      - name: superfluous-else
      #- name: confusing-naming
      - name: get-return
      - name: modifies-parameter
      - name: confusing-results
      - name: deep-exit
      - name: unused-parameter
      - name: unreachable-code
      #- name: add-constant
      #  arguments:
      #    - maxLitCount: "3"
      #      allowStrs: '""'
      #      allowInts: "0,1,2"
      #      allowFloats: "0.0,0.,1.0,1.,2.0,2."
      - name: flag-parameter
      - name: unnecessary-stmt
      - name: struct-tag
      - name: modifies-value-receiver
      - name: constant-logical-expr
      - name: bool-literal-in-expr
      - name: redefines-builtin-id
      #- name: function-result-limit
      #  arguments: 3
      - name: imports-blacklist
      #  arguments: ["crypto/md5", "crypto/sha1"]
      - name: range-val-in-closure
      - name: range-val-address
      - name: waitgroup-by-value
      - name: atomic
      - name: empty-lines
      #- name: line-length-limit
      #  arguments: 80
      - name: call-to-gc
      - name: duplicated-imports
      #- name: import-shadowing # See https://github.com/mgechev/revive/issues/534
      #- name: bare-return
      - name: unused-receiver
      #- name: unhandled-error
      #  arguments:
      #    - os.Setenv
      #    - os.Unsetenv
      #    - fmt.Print
      #    - fmt.Printf
      #    - fmt.Println
      #- name: cognitive-complexity
      #  arguments: 15
      - name: string-of-int
      - name: string-format
        arguments:
          - [ "fmt.Errorf[0]", "/(^|[^\\.!?])$/", "must not end in punctuation" ]
          - [ "panic", "/^[^\\n]*$/", "must not contain line breaks" ]
      - name: early-return
      - name: unconditional-recursion
      - name: identical-branches
      - name: defer
        # Options: call-chain, loop, method-call, recover, return.
        # By default all enabled.
        #arguments: [["loop","recover","return"]]
      - name: unexported-naming
      #- name: function-length
      #  arguments: [40, 60]

  lll:
    line-length: 150
    tab-width: 1

  maligned:
    suggest-new: true

  tagliatelle:
    # check the struck tag name case
    case:
      # use the struct field name to check the name of the struct tag
      use-field-name: true
      rules:
        # any struct tag type can be used.
        # support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json: snake
        yaml: snake

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - golint # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - ifshort # questionable
    - wrapcheck # questionable
    - exhaustivestruct # questionable
    - wsl # strange behavior
    - godox # strange behavior
    - gci # strange behavior
    - varnamelen # strange behavior
    - exhaustruct # strange behavior
    - nonamedreturns # strange behavior
    - tagliatelle # strange behavior
    - ireturn # strange behavior
    - nosnakecase # deprecated
    - nilerr #
    - interfacebloat # is not configurable https://golangci-lint.run/usage/linters/#interfacebloat
    - contextcheck
    - varcheck # deprecated
    - deadcode # deprecated
    - structcheck # deprecated
  fast: false
