version: "2"
run:
  tests: true
linters:
  default: standard
  disable:
    - gci
    - varnamelen
  settings:
    depguard:
      rules:
        cmd:
          files:
            - cmd/*/*.go
          allow:
            - $gostd
        main:
          files:
            - ""
          allow:
            - $gostd
        tests:
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr/testify
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
    rules:
      - linters:
          - ireturn
        text: returns generic interface
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - errcheck
        source: defer\s+[^\s]+.Close()
      - linters:
          - revive
        text: 'unexported-return: exported func .+ returns unexported type .+, which can be annoying to use'
      - path: cmd/[^/]+/.+\.go
        text: exitAfterDefer
      - path: internal/connect/commits_helpers.go
        linters:
          - staticcheck
      - path: internal/providers/bitbucket/repos.go
        linters:
          - staticcheck
      - path: internal/providers/github/repos.go
        linters:
          - staticcheck
      - path: internal/providers/bitbucket/getrepo_test.go
        linters:
          - staticcheck
      - path: internal/providers/multisource/repo.go
        linters:
          - ineffassign
          - staticcheck
      - path: internal/connect/api.go
        linters:
          - errcheck
      - path: e2e/testutil/server.go
        linters:
          - errcheck
      - path: internal/providers/content/helpers.go
        linters:
          - staticcheck
      - linters:
          - dupl
          - errcheck
          - exhaustruct
          - funlen
          - gochecknoglobals
          - gocyclo
          - gosec
          - ineffassign
          - ireturn
          - lll
          - staticcheck
          - unused
          - unparam
        path: _test\.go
    paths:
      - bin
      - config
      - debian
      - docs
      - scripts
      - tests
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/easyp-tech)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - bin
      - config
      - debian
      - docs
      - scripts
      - tests
      - third_party$
      - builtin$
      - examples$
