// Copyright 2020-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: buf/alpha/registry/v1alpha1/authz.proto

package registryv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthzService_UserCanCreateOrganizationRepository_FullMethodName = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanCreateOrganizationRepository"
	AuthzService_UserCanSeeRepositorySettings_FullMethodName        = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanSeeRepositorySettings"
	AuthzService_UserCanSeeOrganizationSettings_FullMethodName      = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanSeeOrganizationSettings"
	AuthzService_UserCanAddOrganizationMember_FullMethodName        = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanAddOrganizationMember"
	AuthzService_UserCanUpdateOrganizationMember_FullMethodName     = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanUpdateOrganizationMember"
	AuthzService_UserCanRemoveOrganizationMember_FullMethodName     = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanRemoveOrganizationMember"
	AuthzService_UserCanDeleteOrganization_FullMethodName           = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanDeleteOrganization"
	AuthzService_UserCanDeleteRepository_FullMethodName             = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanDeleteRepository"
	AuthzService_UserCanDeleteUser_FullMethodName                   = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanDeleteUser"
	AuthzService_UserCanSeeServerAdminPanel_FullMethodName          = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanSeeServerAdminPanel"
	AuthzService_UserCanManageRepositoryContributors_FullMethodName = "/buf.alpha.registry.v1alpha1.AuthzService/UserCanManageRepositoryContributors"
)

// AuthzServiceClient is the client API for AuthzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthzServiceClient interface {
	// UserCanCreateOrganizationRepository returns whether the user is authorized
	// to create repositories in an organization.
	UserCanCreateOrganizationRepository(ctx context.Context, in *UserCanCreateOrganizationRepositoryRequest, opts ...grpc.CallOption) (*UserCanCreateOrganizationRepositoryResponse, error)
	// UserCanSeeRepositorySettings returns whether the user is authorized
	// to see repository settings.
	UserCanSeeRepositorySettings(ctx context.Context, in *UserCanSeeRepositorySettingsRequest, opts ...grpc.CallOption) (*UserCanSeeRepositorySettingsResponse, error)
	// UserCanSeeOrganizationSettings returns whether the user is authorized
	// to see organization settings.
	UserCanSeeOrganizationSettings(ctx context.Context, in *UserCanSeeOrganizationSettingsRequest, opts ...grpc.CallOption) (*UserCanSeeOrganizationSettingsResponse, error)
	// UserCanAddOrganizationMember returns whether the user is authorized to add
	// any members to the organization and the list of roles they can add.
	UserCanAddOrganizationMember(ctx context.Context, in *UserCanAddOrganizationMemberRequest, opts ...grpc.CallOption) (*UserCanAddOrganizationMemberResponse, error)
	// UserCanUpdateOrganizationMember returns whether the user is authorized to update
	// any members' membership information in the organization and the list of roles they can update.
	UserCanUpdateOrganizationMember(ctx context.Context, in *UserCanUpdateOrganizationMemberRequest, opts ...grpc.CallOption) (*UserCanUpdateOrganizationMemberResponse, error)
	// UserCanRemoveOrganizationMember returns whether the user is authorized to remove
	// any members from the organization and the list of roles they can remove.
	UserCanRemoveOrganizationMember(ctx context.Context, in *UserCanRemoveOrganizationMemberRequest, opts ...grpc.CallOption) (*UserCanRemoveOrganizationMemberResponse, error)
	// UserCanDeleteOrganization returns whether the user is authorized
	// to delete an organization.
	UserCanDeleteOrganization(ctx context.Context, in *UserCanDeleteOrganizationRequest, opts ...grpc.CallOption) (*UserCanDeleteOrganizationResponse, error)
	// UserCanDeleteRepository returns whether the user is authorized
	// to delete a repository.
	UserCanDeleteRepository(ctx context.Context, in *UserCanDeleteRepositoryRequest, opts ...grpc.CallOption) (*UserCanDeleteRepositoryResponse, error)
	// UserCanDeleteUser returns whether the user is authorized
	// to delete a user.
	UserCanDeleteUser(ctx context.Context, in *UserCanDeleteUserRequest, opts ...grpc.CallOption) (*UserCanDeleteUserResponse, error)
	// UserCanSeeServerAdminPanel returns whether the user is authorized
	// to see server admin panel.
	UserCanSeeServerAdminPanel(ctx context.Context, in *UserCanSeeServerAdminPanelRequest, opts ...grpc.CallOption) (*UserCanSeeServerAdminPanelResponse, error)
	// UserCanManageRepositoryContributors returns whether the user is authorized to manage
	// any contributors to the repository and the list of roles they can manage.
	UserCanManageRepositoryContributors(ctx context.Context, in *UserCanManageRepositoryContributorsRequest, opts ...grpc.CallOption) (*UserCanManageRepositoryContributorsResponse, error)
}

type authzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthzServiceClient(cc grpc.ClientConnInterface) AuthzServiceClient {
	return &authzServiceClient{cc}
}

func (c *authzServiceClient) UserCanCreateOrganizationRepository(ctx context.Context, in *UserCanCreateOrganizationRepositoryRequest, opts ...grpc.CallOption) (*UserCanCreateOrganizationRepositoryResponse, error) {
	out := new(UserCanCreateOrganizationRepositoryResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanCreateOrganizationRepository_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanSeeRepositorySettings(ctx context.Context, in *UserCanSeeRepositorySettingsRequest, opts ...grpc.CallOption) (*UserCanSeeRepositorySettingsResponse, error) {
	out := new(UserCanSeeRepositorySettingsResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanSeeRepositorySettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanSeeOrganizationSettings(ctx context.Context, in *UserCanSeeOrganizationSettingsRequest, opts ...grpc.CallOption) (*UserCanSeeOrganizationSettingsResponse, error) {
	out := new(UserCanSeeOrganizationSettingsResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanSeeOrganizationSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanAddOrganizationMember(ctx context.Context, in *UserCanAddOrganizationMemberRequest, opts ...grpc.CallOption) (*UserCanAddOrganizationMemberResponse, error) {
	out := new(UserCanAddOrganizationMemberResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanAddOrganizationMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanUpdateOrganizationMember(ctx context.Context, in *UserCanUpdateOrganizationMemberRequest, opts ...grpc.CallOption) (*UserCanUpdateOrganizationMemberResponse, error) {
	out := new(UserCanUpdateOrganizationMemberResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanUpdateOrganizationMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanRemoveOrganizationMember(ctx context.Context, in *UserCanRemoveOrganizationMemberRequest, opts ...grpc.CallOption) (*UserCanRemoveOrganizationMemberResponse, error) {
	out := new(UserCanRemoveOrganizationMemberResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanRemoveOrganizationMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanDeleteOrganization(ctx context.Context, in *UserCanDeleteOrganizationRequest, opts ...grpc.CallOption) (*UserCanDeleteOrganizationResponse, error) {
	out := new(UserCanDeleteOrganizationResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanDeleteOrganization_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanDeleteRepository(ctx context.Context, in *UserCanDeleteRepositoryRequest, opts ...grpc.CallOption) (*UserCanDeleteRepositoryResponse, error) {
	out := new(UserCanDeleteRepositoryResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanDeleteRepository_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanDeleteUser(ctx context.Context, in *UserCanDeleteUserRequest, opts ...grpc.CallOption) (*UserCanDeleteUserResponse, error) {
	out := new(UserCanDeleteUserResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanDeleteUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanSeeServerAdminPanel(ctx context.Context, in *UserCanSeeServerAdminPanelRequest, opts ...grpc.CallOption) (*UserCanSeeServerAdminPanelResponse, error) {
	out := new(UserCanSeeServerAdminPanelResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanSeeServerAdminPanel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) UserCanManageRepositoryContributors(ctx context.Context, in *UserCanManageRepositoryContributorsRequest, opts ...grpc.CallOption) (*UserCanManageRepositoryContributorsResponse, error) {
	out := new(UserCanManageRepositoryContributorsResponse)
	err := c.cc.Invoke(ctx, AuthzService_UserCanManageRepositoryContributors_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthzServiceServer is the server API for AuthzService service.
// All implementations should embed UnimplementedAuthzServiceServer
// for forward compatibility
type AuthzServiceServer interface {
	// UserCanCreateOrganizationRepository returns whether the user is authorized
	// to create repositories in an organization.
	UserCanCreateOrganizationRepository(context.Context, *UserCanCreateOrganizationRepositoryRequest) (*UserCanCreateOrganizationRepositoryResponse, error)
	// UserCanSeeRepositorySettings returns whether the user is authorized
	// to see repository settings.
	UserCanSeeRepositorySettings(context.Context, *UserCanSeeRepositorySettingsRequest) (*UserCanSeeRepositorySettingsResponse, error)
	// UserCanSeeOrganizationSettings returns whether the user is authorized
	// to see organization settings.
	UserCanSeeOrganizationSettings(context.Context, *UserCanSeeOrganizationSettingsRequest) (*UserCanSeeOrganizationSettingsResponse, error)
	// UserCanAddOrganizationMember returns whether the user is authorized to add
	// any members to the organization and the list of roles they can add.
	UserCanAddOrganizationMember(context.Context, *UserCanAddOrganizationMemberRequest) (*UserCanAddOrganizationMemberResponse, error)
	// UserCanUpdateOrganizationMember returns whether the user is authorized to update
	// any members' membership information in the organization and the list of roles they can update.
	UserCanUpdateOrganizationMember(context.Context, *UserCanUpdateOrganizationMemberRequest) (*UserCanUpdateOrganizationMemberResponse, error)
	// UserCanRemoveOrganizationMember returns whether the user is authorized to remove
	// any members from the organization and the list of roles they can remove.
	UserCanRemoveOrganizationMember(context.Context, *UserCanRemoveOrganizationMemberRequest) (*UserCanRemoveOrganizationMemberResponse, error)
	// UserCanDeleteOrganization returns whether the user is authorized
	// to delete an organization.
	UserCanDeleteOrganization(context.Context, *UserCanDeleteOrganizationRequest) (*UserCanDeleteOrganizationResponse, error)
	// UserCanDeleteRepository returns whether the user is authorized
	// to delete a repository.
	UserCanDeleteRepository(context.Context, *UserCanDeleteRepositoryRequest) (*UserCanDeleteRepositoryResponse, error)
	// UserCanDeleteUser returns whether the user is authorized
	// to delete a user.
	UserCanDeleteUser(context.Context, *UserCanDeleteUserRequest) (*UserCanDeleteUserResponse, error)
	// UserCanSeeServerAdminPanel returns whether the user is authorized
	// to see server admin panel.
	UserCanSeeServerAdminPanel(context.Context, *UserCanSeeServerAdminPanelRequest) (*UserCanSeeServerAdminPanelResponse, error)
	// UserCanManageRepositoryContributors returns whether the user is authorized to manage
	// any contributors to the repository and the list of roles they can manage.
	UserCanManageRepositoryContributors(context.Context, *UserCanManageRepositoryContributorsRequest) (*UserCanManageRepositoryContributorsResponse, error)
}

// UnimplementedAuthzServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAuthzServiceServer struct {
}

func (UnimplementedAuthzServiceServer) UserCanCreateOrganizationRepository(context.Context, *UserCanCreateOrganizationRepositoryRequest) (*UserCanCreateOrganizationRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanCreateOrganizationRepository not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanSeeRepositorySettings(context.Context, *UserCanSeeRepositorySettingsRequest) (*UserCanSeeRepositorySettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanSeeRepositorySettings not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanSeeOrganizationSettings(context.Context, *UserCanSeeOrganizationSettingsRequest) (*UserCanSeeOrganizationSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanSeeOrganizationSettings not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanAddOrganizationMember(context.Context, *UserCanAddOrganizationMemberRequest) (*UserCanAddOrganizationMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanAddOrganizationMember not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanUpdateOrganizationMember(context.Context, *UserCanUpdateOrganizationMemberRequest) (*UserCanUpdateOrganizationMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanUpdateOrganizationMember not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanRemoveOrganizationMember(context.Context, *UserCanRemoveOrganizationMemberRequest) (*UserCanRemoveOrganizationMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanRemoveOrganizationMember not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanDeleteOrganization(context.Context, *UserCanDeleteOrganizationRequest) (*UserCanDeleteOrganizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanDeleteOrganization not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanDeleteRepository(context.Context, *UserCanDeleteRepositoryRequest) (*UserCanDeleteRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanDeleteRepository not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanDeleteUser(context.Context, *UserCanDeleteUserRequest) (*UserCanDeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanDeleteUser not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanSeeServerAdminPanel(context.Context, *UserCanSeeServerAdminPanelRequest) (*UserCanSeeServerAdminPanelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanSeeServerAdminPanel not implemented")
}
func (UnimplementedAuthzServiceServer) UserCanManageRepositoryContributors(context.Context, *UserCanManageRepositoryContributorsRequest) (*UserCanManageRepositoryContributorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCanManageRepositoryContributors not implemented")
}

// UnsafeAuthzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthzServiceServer will
// result in compilation errors.
type UnsafeAuthzServiceServer interface {
	mustEmbedUnimplementedAuthzServiceServer()
}

func RegisterAuthzServiceServer(s grpc.ServiceRegistrar, srv AuthzServiceServer) {
	s.RegisterService(&AuthzService_ServiceDesc, srv)
}

func _AuthzService_UserCanCreateOrganizationRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanCreateOrganizationRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanCreateOrganizationRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanCreateOrganizationRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanCreateOrganizationRepository(ctx, req.(*UserCanCreateOrganizationRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanSeeRepositorySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanSeeRepositorySettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanSeeRepositorySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanSeeRepositorySettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanSeeRepositorySettings(ctx, req.(*UserCanSeeRepositorySettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanSeeOrganizationSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanSeeOrganizationSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanSeeOrganizationSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanSeeOrganizationSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanSeeOrganizationSettings(ctx, req.(*UserCanSeeOrganizationSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanAddOrganizationMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanAddOrganizationMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanAddOrganizationMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanAddOrganizationMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanAddOrganizationMember(ctx, req.(*UserCanAddOrganizationMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanUpdateOrganizationMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanUpdateOrganizationMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanUpdateOrganizationMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanUpdateOrganizationMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanUpdateOrganizationMember(ctx, req.(*UserCanUpdateOrganizationMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanRemoveOrganizationMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanRemoveOrganizationMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanRemoveOrganizationMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanRemoveOrganizationMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanRemoveOrganizationMember(ctx, req.(*UserCanRemoveOrganizationMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanDeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanDeleteOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanDeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanDeleteOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanDeleteOrganization(ctx, req.(*UserCanDeleteOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanDeleteRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanDeleteRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanDeleteRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanDeleteRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanDeleteRepository(ctx, req.(*UserCanDeleteRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanDeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanDeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanDeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanDeleteUser(ctx, req.(*UserCanDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanSeeServerAdminPanel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanSeeServerAdminPanelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanSeeServerAdminPanel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanSeeServerAdminPanel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanSeeServerAdminPanel(ctx, req.(*UserCanSeeServerAdminPanelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_UserCanManageRepositoryContributors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCanManageRepositoryContributorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).UserCanManageRepositoryContributors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_UserCanManageRepositoryContributors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).UserCanManageRepositoryContributors(ctx, req.(*UserCanManageRepositoryContributorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthzService_ServiceDesc is the grpc.ServiceDesc for AuthzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buf.alpha.registry.v1alpha1.AuthzService",
	HandlerType: (*AuthzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserCanCreateOrganizationRepository",
			Handler:    _AuthzService_UserCanCreateOrganizationRepository_Handler,
		},
		{
			MethodName: "UserCanSeeRepositorySettings",
			Handler:    _AuthzService_UserCanSeeRepositorySettings_Handler,
		},
		{
			MethodName: "UserCanSeeOrganizationSettings",
			Handler:    _AuthzService_UserCanSeeOrganizationSettings_Handler,
		},
		{
			MethodName: "UserCanAddOrganizationMember",
			Handler:    _AuthzService_UserCanAddOrganizationMember_Handler,
		},
		{
			MethodName: "UserCanUpdateOrganizationMember",
			Handler:    _AuthzService_UserCanUpdateOrganizationMember_Handler,
		},
		{
			MethodName: "UserCanRemoveOrganizationMember",
			Handler:    _AuthzService_UserCanRemoveOrganizationMember_Handler,
		},
		{
			MethodName: "UserCanDeleteOrganization",
			Handler:    _AuthzService_UserCanDeleteOrganization_Handler,
		},
		{
			MethodName: "UserCanDeleteRepository",
			Handler:    _AuthzService_UserCanDeleteRepository_Handler,
		},
		{
			MethodName: "UserCanDeleteUser",
			Handler:    _AuthzService_UserCanDeleteUser_Handler,
		},
		{
			MethodName: "UserCanSeeServerAdminPanel",
			Handler:    _AuthzService_UserCanSeeServerAdminPanel_Handler,
		},
		{
			MethodName: "UserCanManageRepositoryContributors",
			Handler:    _AuthzService_UserCanManageRepositoryContributors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buf/alpha/registry/v1alpha1/authz.proto",
}
