// Copyright 2020-2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: buf/alpha/registry/v1alpha1/search.proto

package registryv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SearchService_Search_FullMethodName              = "/buf.alpha.registry.v1alpha1.SearchService/Search"
	SearchService_SearchTag_FullMethodName           = "/buf.alpha.registry.v1alpha1.SearchService/SearchTag"
	SearchService_SearchDraft_FullMethodName         = "/buf.alpha.registry.v1alpha1.SearchService/SearchDraft"
	SearchService_SearchModuleContent_FullMethodName = "/buf.alpha.registry.v1alpha1.SearchService/SearchModuleContent"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	// Search searches the BSR.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// SearchTag searches for tags in a repository
	SearchTag(ctx context.Context, in *SearchTagRequest, opts ...grpc.CallOption) (*SearchTagResponse, error)
	// SearchDraft searches for drafts in a repository
	SearchDraft(ctx context.Context, in *SearchDraftRequest, opts ...grpc.CallOption) (*SearchDraftResponse, error)
	// SearchModuleContent searches for module contents on the BSR.
	SearchModuleContent(ctx context.Context, in *SearchModuleContentRequest, opts ...grpc.CallOption) (*SearchModuleContentResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchService_Search_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchTag(ctx context.Context, in *SearchTagRequest, opts ...grpc.CallOption) (*SearchTagResponse, error) {
	out := new(SearchTagResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchTag_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchDraft(ctx context.Context, in *SearchDraftRequest, opts ...grpc.CallOption) (*SearchDraftResponse, error) {
	out := new(SearchDraftResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchDraft_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchModuleContent(ctx context.Context, in *SearchModuleContentRequest, opts ...grpc.CallOption) (*SearchModuleContentResponse, error) {
	out := new(SearchModuleContentResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchModuleContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations should embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	// Search searches the BSR.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// SearchTag searches for tags in a repository
	SearchTag(context.Context, *SearchTagRequest) (*SearchTagResponse, error)
	// SearchDraft searches for drafts in a repository
	SearchDraft(context.Context, *SearchDraftRequest) (*SearchDraftResponse, error)
	// SearchModuleContent searches for module contents on the BSR.
	SearchModuleContent(context.Context, *SearchModuleContentRequest) (*SearchModuleContentResponse, error)
}

// UnimplementedSearchServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchServiceServer) SearchTag(context.Context, *SearchTagRequest) (*SearchTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTag not implemented")
}
func (UnimplementedSearchServiceServer) SearchDraft(context.Context, *SearchDraftRequest) (*SearchDraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDraft not implemented")
}
func (UnimplementedSearchServiceServer) SearchModuleContent(context.Context, *SearchModuleContentRequest) (*SearchModuleContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchModuleContent not implemented")
}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchTag(ctx, req.(*SearchTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchDraft(ctx, req.(*SearchDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchModuleContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchModuleContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchModuleContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchModuleContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchModuleContent(ctx, req.(*SearchModuleContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buf.alpha.registry.v1alpha1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
		{
			MethodName: "SearchTag",
			Handler:    _SearchService_SearchTag_Handler,
		},
		{
			MethodName: "SearchDraft",
			Handler:    _SearchService_SearchDraft_Handler,
		},
		{
			MethodName: "SearchModuleContent",
			Handler:    _SearchService_SearchModuleContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buf/alpha/registry/v1alpha1/search.proto",
}
