name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run unit tests
        run: go test ./... -race -count=1
